// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCeMlKBK_Frr8QD3akBe-nNzwFlYOwSPWM',
    appId: '1:627508428819:web:ddeaa0888b0d845705ffe6',
    messagingSenderId: '627508428819',
    projectId: 'my-notes-dara',
    authDomain: 'my-notes-dara.firebaseapp.com',
    storageBucket: 'my-notes-dara.appspot.com',
    measurementId: 'G-RKFZGY37HV',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBAN31vwJbkQT0aSv5FB-mVTbhfIwhJTwU',
    appId: '1:627508428819:android:9cf17aa170665b0905ffe6',
    messagingSenderId: '627508428819',
    projectId: 'my-notes-dara',
    storageBucket: 'my-notes-dara.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAFv95Ma7vSDYpUCsKI0j3Y2k4-lMA13qE',
    appId: '1:627508428819:ios:5d1c0279a8a62cc205ffe6',
    messagingSenderId: '627508428819',
    projectId: 'my-notes-dara',
    storageBucket: 'my-notes-dara.appspot.com',
    iosClientId: '627508428819-6qihn73s5a7nd6tn64j27opbf99459rq.apps.googleusercontent.com',
    iosBundleId: 'com.moria.app.mynotes',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAFv95Ma7vSDYpUCsKI0j3Y2k4-lMA13qE',
    appId: '1:627508428819:ios:5d1c0279a8a62cc205ffe6',
    messagingSenderId: '627508428819',
    projectId: 'my-notes-dara',
    storageBucket: 'my-notes-dara.appspot.com',
    iosClientId: '627508428819-6qihn73s5a7nd6tn64j27opbf99459rq.apps.googleusercontent.com',
    iosBundleId: 'com.moria.app.mynotes',
  );
}
